[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  # more info here: https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev
  command = "pnpm dev"
  targetPort = 7000 # VueJS port
  framework = "#custom"
  functionsPort = 2000 # netlify functions
  port = 8000
  #[dev.https]
    #certFile = "localhost.pem" # path to the certificate file
    #keyFile = "localhost-key.pem" # path to the private key file
